version: '3'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # RedisInsight (web UI)
    volumes:
      - redis_data:/data
      - ./redis-stack.conf:/redis-stack.conf
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    command: ["redis-server", "/redis-stack.conf"]

volumes:
  redis_data:
    driver: local
