apiVersion: 1

datasources:
  # Main Prometheus datasource - default one
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
    uid: prometheus
    version: 1
    
  # Special datasource for dashboard templating compatibility
  - name: DS_PROMETHEUS
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: true
    uid: ds_prometheus
    version: 1
