# Default Configuration for RAG Dataset Builder
# This file contains default settings that can be overridden by other configuration files

# Directories
directories:
  input: "./data/input"
  output: "./data/output"
  cache: "./.cache"
  logs: "./logs"

# Processing settings
processing:
  batch_size: 10
  max_workers: 4
  max_retries: 3
  timeout: 600  # seconds

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  log_to_file: true
  log_file: "${directories.logs}/rag_dataset_builder.log"

# Plugin discovery settings
plugins:
  auto_discover: true
  scan_directories:
    - "src/implementations"
    - "src/processors"
    - "src/chunkers"
    - "src/embedders"
    - "src/formatters"
    - "src/collectors"
    - "src/trackers"
    - "src/storage"

# Default licensing settings for collected data
licensing:
  default_license: "CC BY-NC-SA 4.0"
  track_license_info: true
  require_attribution: true
  allow_commercial_use: false
  attribution_template: "This dataset includes content from ${source}, licensed under ${license}."

# Defaults for document collection
collection:
  max_documents_per_category: 100
  max_download_size_mb: 500
  excluded_domains: []
  download_delay: 1.0  # seconds
  scrape_images: false

# Performance tracking defaults
tracking:
  enabled: true
  track_system_resources: true
  track_gpu_metrics: true
  metrics_interval: 30  # seconds
