global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting rules
rule_files:
  # - "alert_rules.yml"

# Scrape configuration
scrape_configs:

  - job_name: 'dcgm'
    static_configs:
      - targets: ['dcgm-exporter:9400']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Removed cadvisor job due to compatibility issues
  # We'll rely on DCGM for GPU metrics and node-exporter for system metrics

  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']
      
  # GPU Metrics are collected via node-exporter textfile collector
  
  # Direct GPU metrics exporter
  - job_name: 'gpu-metrics'
    static_configs:
      - targets: ['192.168.1.202:9400']
        labels:
          instance: 'gpu-exporter'
  
  # Add targets for PathRAG and GraphRAG containers
  - job_name: 'hades-containers'
    static_configs:
      - targets: ['hades:9000']  # Assumes we'll expose metrics on this port
        labels:
          experiment: 'hades'
