global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting rules
rule_files:
  # - "alert_rules.yml"

# Scrape configuration
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']
  
  # Add targets for PathRAG and GraphRAG containers
  - job_name: 'hades-containers'
    static_configs:
      - targets: ['hades:9000']  # Assumes we'll expose metrics on this port
        labels:
          experiment: 'hades'
