# RAG Dataset Builder Configuration

# Input data directory
data_dir: "../data"

# Output directory for the RAG dataset
output_dir: "../database"

# Input file pattern configuration
input:
  include:
    - "**/*.pdf"
    - "**/*.txt"
    - "**/*.md"
    - "**/*.py"
    - "**/*.js"
    - "**/*.java"
  exclude:
    - "**/README.md"
    - "**/LICENSE"
    - "**/.git/**"

# Document processor configuration
processor:
  type: "auto"  # Options: auto, simple_text, pdf, code
  # auto will select the appropriate processor based on file extension

# Text chunking configuration
chunker:
  type: "semantic"  # Options: sliding_window, semantic, fixed_size
  chunk_size: 300  # Maximum chunk size (words for sliding_window, characters for semantic)
  chunk_overlap: 50  # Overlap between chunks

# Embedding generation configuration
embedder:
  type: "sentence_transformer"  # Options: sentence_transformer, openai
  model_name: "all-MiniLM-L6-v2"  # Embedding model name
  batch_size: 32  # Batch size for embedding generation
  use_gpu: true  # Use GPU acceleration (will use your RTX A6000 GPUs)

# Output formatter configuration
formatter:
  type: "pathrag"  # Options: pathrag, vector_db, huggingface
  # For vector_db, you can specify the vector database type
  # vector_db_type: "faiss"  # Options: faiss, chroma, milvus

# Processing configuration
processing:
  batch_size: 5  # Number of documents to process in each batch
  num_workers: 2  # Number of parallel workers (matching your 2 GPUs)

# Performance tracking
performance_tracking:
  enabled: true
  arize_phoenix:
    host: "localhost"
    port: 8084  # Updated to match your container configuration

# Search terms for collecting documents
search_terms:
  # Anthropology of Value
  anthropology_value:
    - "anthropology of value"
    - "David Graeber value theory"
    - "Bruce Owens anthropology"
    - "value anthropology STS"
    - "gift exchange theory"
    - "cultural valuation processes"
    
  # Science and Technology Studies
  sts:
    - "science and technology studies"
    - "actor-network theory"
    - "digital sociology"
    - "STS methodology"
    - "social construction of technology"
    - "technological determinism critique"
    
  # Technology Architecture
  tech_architecture:
    - "code analysis architecture"
    - "scaling laws technology"
    - "software architecture patterns"
    - "technical debt management"
    - "architectural evolution systems"
    - "design patterns software"

  # Critics and Alternative Viewpoints
  critics:
    - "Graeber value theory critique"
    - "alternative value frameworks"
    - "critique of gift exchange theory"
    - "limitations of ANT"
    - "critical perspectives on STS"
