# RAG Dataset Builder Configuration for Anthropology of Value and STS
# This configuration includes search terms relevant to anthropology of value and STS
# and integrates with Arize Phoenix for performance tracking

# Input/Output directories
data_dir: "./data/sts_anthropology"
output_dir: "./output/sts_anthropology"

# Collection settings
collection:
  enabled: true
  type: "academic"
  source: "arxiv"
  max_papers_per_term: 50
  search_terms:
    # Anthropology of Value
    - "anthropology of value"
    - "value systems anthropology"
    - "cultural value exchange"
    - "economic anthropology"
    - "gift economy"
    - "value creation anthropology"
    - "moral economy"
    - "exchange theory anthropology"
    - "cultural capital"
    - "symbolic value anthropology"
    
    # Science and Technology Studies (STS)
    - "science and technology studies"
    - "actor network theory"
    - "technological determinism"
    - "sociotechnical systems"
    - "social construction of technology"
    - "technoscience"
    - "technology sociology"
    - "feminist technoscience"
    - "technological infrastructure"
    - "science policy"
    
    # Intersection of Both Fields
    - "value in technological systems"
    - "ethics in technology anthropology"
    - "cultural impact of technology"
    - "indigenous knowledge technology"
    - "digital anthropology"
    - "anthropology of computing"
    - "technology adoption cultures"
    - "value-sensitive design"

# Document processor settings
processor:
  type: "pdf"  # Options: simple_text, pdf, code
  extract_metadata: true
  fallback_to_pdfminer: true

# Chunking settings
chunker:
  type: "sliding_window"  # Options: sliding_window, semantic, fixed_size
  chunk_size: 500
  overlap: 100
  respect_sentences: true
  min_chunk_size: 100

# Embedding settings
embedder:
  type: "sentence_transformer"  # Options: sentence_transformer, openai
  model_name: "all-MiniLM-L6-v2"
  cache_embeddings: true
  batch_size: 32
  use_gpu: true  # Set to true if you have GPU support

# Output format settings
output:
  format: "pathrag"  # Options: pathrag, vector_db, huggingface
  vector_db_type: "faiss"  # Only used if format is vector_db
  include_metadata: true
  save_raw_text: true
  save_raw_embeddings: true

# Performance tracking with Arize Phoenix
performance_tracking:
  enabled: true
  project_name: "rag_dataset_builder"
  phoenix_url: "http://localhost:8084"
  batch_size: 100
  track_document_processing: true
  track_chunking: true
  track_embedding_generation: true
  track_output_generation: true

# Logging settings
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_to_file: true
  log_file: "./logs/rag_dataset_builder.log"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
